#<--- Python case senstive --->

a = 'Sanjeevakumar'
print(a.isupper())
print(a.islower())
print(a.capitalize())
print(a.title())
print(a.upper())
print(a.lower())
print(a.endswith("ar"))
print(a.replace("r", 'ra'))
print(a.count("a"))
print(len(a))
print(a.split(','))
print(a[0])
print(a.find("e"))
print(a.split(" "))
print("Is AlphaNumeric : ", a.isalnum())
print("Is Alpha : ", a.isalpha())
print(','.join(a))
print(a[0:5])
print(a[-5:-1])
print(a[0:])
print(a[::-1])